name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      #- name: Clone openbabel
      #  run: |
      #    pip download openbabel==3.1.1.1
      #    tar xzvf openbabel-3.1.1.1.tar.gz
      #    mv openbabel-3.1.1.1/* .
      #    rm -rf openbabel-3.1.1.1
      - name: Download openbabel
        run: |
          wget https://github.com/openbabel/openbabel/archive/refs/tags/openbabel-3-1-1.tar.gz
          tar xzf openbabel-3-1-1.tar.gz
          mv openbabel-openbabel-3-1-1/* .
          mkdir openbabel

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_SKIP: pp* *musllinux*
          CIBW_ARCHS: native
          CIBW_BUILD_VERBOSITY: 0
          CIBW_BEFORE_BUILD_MACOS: brew install swig eigen
          CIBW_BEFORE_BUILD_LINUX: yum install -y wget libxml2-devel zlib-devel eigen3-devel

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl

