name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone openbabel
        run: |
          pip download openbabel==3.1.1.1
          tar xzvf openbabel-3.1.1.1.tar.gz
          
          mv openbabel-3.1.1.1/* .
          rm -rf openbabel-3.1.1.1

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS: native
          CIBW_SKIP: pp*
          CIBW_BUILD_VERBOSITY: 0
          CIBW_BEFORE_BUILD_MACOS: brew install libxml2 zlib eigen; bash ./openbabel_install.sh
          CIBW_BEFORE_BUILD_LINUX: yum install libxml2-devel zlib-devel eigen3-devel; bash ./openbabel_install.sh

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
