name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      #- name: Clone openbabel
      #  run: |
      #    pip download openbabel==3.1.1.1
      #    tar xzvf openbabel-3.1.1.1.tar.gz
      #    mv openbabel-3.1.1.1/* .
      #    rm -rf openbabel-3.1.1.1

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: cp38-macosx_x86_64 cp38-manylinux_x86_64
          CIBW_BUILD_VERBOSITY: 0
          CIBW_BEFORE_BUILD_MACOS: brew install open-babel && brew list open-babel
          CIBW_BEFORE_BUILD_LINUX: yum install -y wget libxml2-devel zlib-devel eigen3-devel && bash ./openbabel_install.sh
          CIBW_ENVIRONMENT_MACOS: PKG_CONFIG_PATH=/usr/local/Cellar/open-babel/3.1.1_1/lib/pkgconfig/

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl

