name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, macos-10.15]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Download openbabel
        run: |
          which python
          wget -q https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/openbabel-3.1.1-source.tar.bz2
          tar xjf openbabel-3.1.1-source.tar.bz2
          mv openbabel-3.1.1/* .
          rm openbabel-3.1.1-source.tar.bz2
          rm -rf openbabel-3.1.1
          sed -i 's/        install(TARGETS bindings_python/        set(PYOBABEL_INSTDIR ".")\n        install(TARGETS bindings_python/' scripts/CMakeLists.txt 
          cat scripts/CMakeLists.txt

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_SKIP: pp* *musllinux*
          CIBW_BUILD: cp39-*
          CIBW_ARCHS: native
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD_MACOS: brew install swig eigen
          CIBW_BEFORE_BUILD_LINUX: yum install -y swig eigen3-devel

      - run: |
          ls -l wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl

