name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        #os: [macos-10.15]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Download openbabel
        run: |
          which python
          pip3 download openbabel==3.1.1.1
          tar xzf openbabel-3.1.1.1.tar.gz
          mv openbabel-3.1.1.1/* .
          rm openbabel-3.1.1.1.tar.gz
          rm -rf openbabel-3.1.1.1
          rm setup.py
          mv obsetup.py setup.py

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.11.1
        env:
          CIBW_SKIP: pp* *musllinux*
          CIBW_BUILD: cp38-*
          CIBW_ARCHS: native
          CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_BUILD_MACOS: brew install open-babel
          CIBW_BEFORE_BUILD_LINUX: dnf install -y epel-release && dnf install -y gcc gcc-c++ swig openbabel-devel

      - run: |
          ls -l wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl

