name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        #os: [macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Download openbabel
        run: |
          which python
          wget -q https://files.pythonhosted.org/packages/92/c5/e010bb31c67383ceeaf724fe945b2cc7de1242ad9e6f673af111f760e22a/openbabel-wheel-3.1.1.5.tar.gz
          tar xzf openbabel-wheel-3.1.1.5.tar.gz
          mv openbabel-wheel-3.1.1.5/* .
          rm openbabel-wheel-3.1.1.5.tar.gz
          rm -rf openbabel-wheel-3.1.1.5
          if [ "$RUNNER_OS" == "Linux" ]; then
            sed -i 's/name="openbabel-wheel"/name="openbabel"/' setup.py
            mv -f CMakeLists.txt.pre scripts/CMakeLists.txt
          else
            sed -i "" 's/name="openbabel-wheel"/name="openbabel"/' setup.py
          fi

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.5.0
        env:
          CIBW_SKIP: pp* *musllinux*
          CIBW_BUILD: cp38-*
          CIBW_ARCHS: native
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD_MACOS: brew install swig eigen cairo
          CIBW_BEFORE_BUILD_LINUX: cmake --version && ls -l /usr/local/lib64/ && yum install -y eigen3-devel cairo-devel swig

      - run: |
          ls -l wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl

